# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.7
  - 1.0
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.build(); Pkg.test("CachedInterpolations")'
after_success:
# update the documentation
  - julia -e 'using Pkg; Pkg.add("Documenter")'
  - julia -e 'using CachedInterpolations; cd(dirname(dirname(pathof(CachedInterpolations)))); ENV["DOCUMENTER_DEBUG"] = "true"; include(joinpath("docs", "make.jl"))'
