name = "CachedInterpolations"
uuid = "b9709bfb-d23d-5560-8276-8c35c4b76823"
authors = ["Tim Holy <tim.holy@gmail.com>"]
version = "0.1.1"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Interpolations = "0.14, 0.15"
StaticArrays = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
